# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eCaretakerWeb', '0005_auto_20160801_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Leave blank if your house has no name yet', max_length=20, verbose_name='House Name')),
                ('house_no', models.CharField(blank=True, help_text='Write your house number or any other description', max_length=20, verbose_name='House No/Description')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.City', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Please enter the name of the local government', max_length=30, verbose_name='Local Government Area')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Please enter the name of the state', max_length=30, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Street Name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.City', verbose_name='City')),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.LGA', verbose_name='Local Government Area')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.State', verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='stateId',
            field=models.ForeignKey(help_text='Please select the local government area state', on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.State', verbose_name='state'),
        ),
        migrations.AddField(
            model_name='house',
            name='local_government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.LGA', verbose_name='Local Government'),
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerWeb.Users', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.Street', verbose_name='Street Name'),
        ),
        migrations.AddField(
            model_name='city',
            name='local_government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.LGA', verbose_name='Local Government Area'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCaretakerLocations.State', verbose_name='State'),
        ),
    ]
