branch-defaults:
  master:
    environment: eCaretaker-dev
global:
  application_name: eCaretaker
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: eu-west-1
  profile: eb-cli
  repository: null
  sc: git
